/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type CtaLink = {
  linkType?: "internal" | "external";
  reference?: PageReference;
  url?: string;
  openInNewTab?: boolean;
};

export type ChildrenCtaLink = {
  linkType?: "internal" | "external";
  reference?: PageReference;
  url?: string;
  openInNewTab?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    link?: ChildrenCtaLink;
    level?: 1 | 2 | 3;
    _type: "cta";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "internal" | "external";
    reference?: PageReference;
    url?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  caption?: string;
  _type: "richTextImage";
  _key: string;
}>;

export type Cta = {
  _type: "cta";
  link?: CtaLink;
  level?: 1 | 2 | 3;
};

export type ImageBlock = {
  _type: "imageBlock";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  caption?: string;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  author?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProjectsGrid = {
  _type: "projectsGrid";
  heading?: string;
  intro?: string;
};

export type ContactSection = {
  _type: "contactSection";
  heading?: string;
  body?: string;
  showContactDetails?: boolean;
};

export type Faq = {
  _type: "faq";
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
};

export type Features = {
  _type: "features";
  heading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?: string;
    _type: "featureItem";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  heading?: string;
  body?: string;
  image?: ImageBlock;
  cta?: Cta;
};

export type Link = {
  _type: "link";
  linkType?: "internal" | "external";
  reference?: PageReference;
  url?: string;
  openInNewTab?: boolean;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteUrl?: string;
  defaultSeo?: Seo;
  email?: string;
  phone?: string;
  address?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  headerLinks?: Array<{
    _key: string;
  } & Link>;
  footerLinks?: Array<{
    _key: string;
  } & Link>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  content?: Array<{
    _key: string;
  } & Hero | {
    _key: string;
  } & Features | {
    _key: string;
  } & Faq | {
    _key: string;
  } & ContactSection | {
    _key: string;
  } & ProjectsGrid | {
    _key: string;
  } & Testimonial | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & Cta | {
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      } | {
        link?: ChildrenCtaLink;
        level?: 1 | 2 | 3;
        _type: "cta";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "internal" | "external";
        reference?: PageReference;
        url?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      caption?: string;
      _type: "richTextImage";
      _key: string;
    }>;
    _type: "richText";
    _key: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  noIndex?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = PageReference | CtaLink | ChildrenCtaLink | SanityImageAssetReference | RichText | Cta | ImageBlock | Testimonial | ProjectsGrid | ContactSection | Faq | Features | Hero | Link | Seo | Project | SanityImageCrop | SanityImageHotspot | Slug | SiteSettings | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../website/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  siteName,  siteUrl,  email,  phone,  address,  socialLinks,  defaultSeo {  title,  description,  noIndex,  ogImage},  headerLinks[]{    _key,    linkType,    url,    openInNewTab,    reference->{ name, "slug": slug.current }  },  footerLinks[]{    _key,    linkType,    url,    openInNewTab,    reference->{ name, "slug": slug.current }  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string | null;
  siteUrl: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  defaultSeo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  headerLinks: Array<{
    _key: string;
    linkType: "external" | "internal" | null;
    url: string | null;
    openInNewTab: boolean | null;
    reference: {
      name: string | null;
      slug: string | null;
    } | null;
  }> | null;
  footerLinks: Array<{
    _key: string;
    linkType: "external" | "internal" | null;
    url: string | null;
    openInNewTab: boolean | null;
    reference: {
      name: string | null;
      slug: string | null;
    } | null;
  }> | null;
} | null;

// Source: ../website/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(title asc) {  _id,  title,  "slug": slug.current,  description,  coverImage}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ../website/src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && slug.current != "home" && (!defined(noIndex) || noIndex != true) && (!defined(seo.noIndex) || seo.noIndex != true)].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../website/src/sanity/queries.ts
// Variable: SITEMAP_PAGES_QUERY
// Query: *[_type == "page" && (!defined(noIndex) || noIndex != true) && (!defined(seo.noIndex) || seo.noIndex != true)]{  "slug": slug.current,  _updatedAt}
export type SITEMAP_PAGES_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: ../website/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "home"][0]{  _id,  name,  "slug": slug.current,  noIndex,  seo {  title,  description,  noIndex,  ogImage},  content[]{    _key,    _type,    _type == "hero" => {      heading,      body,      image,      cta {        level,        link {  linkType,  url,  openInNewTab,  reference->{ name, "slug": slug.current }}      }    },    _type == "features" => {      heading,      items[]{ title, description, icon }    },    _type == "faq" => {      heading,      items[]{ question, answer }    },    _type == "contactSection" => {      heading,      body,      showContactDetails    },    _type == "projectsGrid" => {      heading,      intro    },    _type == "testimonial" => {      quote,      author,      role,      image    },    _type == "imageBlock" => {      asset,      altText,      caption    },    _type == "richText" => {      content    },    _type == "cta" => {      level,      link {  linkType,  url,  openInNewTab,  reference->{ name, "slug": slug.current }}    }  }}
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  noIndex: boolean | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  content: Array<{
    _key: string;
    _type: "contactSection";
    heading: string | null;
    body: string | null;
    showContactDetails: boolean | null;
  } | {
    _key: string;
    _type: "cta";
    level: 1 | 2 | 3 | null;
    link: {
      linkType: "external" | "internal" | null;
      url: string | null;
      openInNewTab: boolean | null;
      reference: {
        name: string | null;
        slug: string | null;
      } | null;
    } | null;
  } | {
    _key: string;
    _type: "faq";
    heading: string | null;
    items: Array<{
      question: string | null;
      answer: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "features";
    heading: string | null;
    items: Array<{
      title: string | null;
      description: string | null;
      icon: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "hero";
    heading: string | null;
    body: string | null;
    image: ImageBlock | null;
    cta: {
      level: 1 | 2 | 3 | null;
      link: {
        linkType: "external" | "internal" | null;
        url: string | null;
        openInNewTab: boolean | null;
        reference: {
          name: string | null;
          slug: string | null;
        } | null;
      } | null;
    } | null;
  } | {
    _key: string;
    _type: "imageBlock";
    asset: SanityImageAssetReference | null;
    altText: string | null;
    caption: string | null;
  } | {
    _key: string;
    _type: "projectsGrid";
    heading: string | null;
    intro: string | null;
  } | {
    _key: string;
    _type: "richText";
    content: Array<{
      children?: Array<{
        link?: ChildrenCtaLink;
        level?: 1 | 2 | 3;
        _type: "cta";
        _key: string;
      } | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "external" | "internal";
        reference?: PageReference;
        url?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      caption?: string;
      _type: "richTextImage";
      _key: string;
    }> | null;
  } | {
    _key: string;
    _type: "testimonial";
    quote: string | null;
    author: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Source: ../website/src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  noIndex,  seo {  title,  description,  noIndex,  ogImage},  content[]{    _key,    _type,    _type == "hero" => {      heading,      body,      image,      cta {        level,        link {  linkType,  url,  openInNewTab,  reference->{ name, "slug": slug.current }}      }    },    _type == "features" => {      heading,      items[]{ title, description, icon }    },    _type == "faq" => {      heading,      items[]{ question, answer }    },    _type == "contactSection" => {      heading,      body,      showContactDetails    },    _type == "projectsGrid" => {      heading,      intro    },    _type == "testimonial" => {      quote,      author,      role,      image    },    _type == "imageBlock" => {      asset,      altText,      caption    },    _type == "richText" => {      content    },    _type == "cta" => {      level,      link {  linkType,  url,  openInNewTab,  reference->{ name, "slug": slug.current }}    }  }}
export type PAGE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  noIndex: boolean | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  content: Array<{
    _key: string;
    _type: "contactSection";
    heading: string | null;
    body: string | null;
    showContactDetails: boolean | null;
  } | {
    _key: string;
    _type: "cta";
    level: 1 | 2 | 3 | null;
    link: {
      linkType: "external" | "internal" | null;
      url: string | null;
      openInNewTab: boolean | null;
      reference: {
        name: string | null;
        slug: string | null;
      } | null;
    } | null;
  } | {
    _key: string;
    _type: "faq";
    heading: string | null;
    items: Array<{
      question: string | null;
      answer: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "features";
    heading: string | null;
    items: Array<{
      title: string | null;
      description: string | null;
      icon: string | null;
    }> | null;
  } | {
    _key: string;
    _type: "hero";
    heading: string | null;
    body: string | null;
    image: ImageBlock | null;
    cta: {
      level: 1 | 2 | 3 | null;
      link: {
        linkType: "external" | "internal" | null;
        url: string | null;
        openInNewTab: boolean | null;
        reference: {
          name: string | null;
          slug: string | null;
        } | null;
      } | null;
    } | null;
  } | {
    _key: string;
    _type: "imageBlock";
    asset: SanityImageAssetReference | null;
    altText: string | null;
    caption: string | null;
  } | {
    _key: string;
    _type: "projectsGrid";
    heading: string | null;
    intro: string | null;
  } | {
    _key: string;
    _type: "richText";
    content: Array<{
      children?: Array<{
        link?: ChildrenCtaLink;
        level?: 1 | 2 | 3;
        _type: "cta";
        _key: string;
      } | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "external" | "internal";
        reference?: PageReference;
        url?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      caption?: string;
      _type: "richTextImage";
      _key: string;
    }> | null;
  } | {
    _key: string;
    _type: "testimonial";
    quote: string | null;
    author: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"siteSettings\"][0]{\n  siteName,\n  siteUrl,\n  email,\n  phone,\n  address,\n  socialLinks,\n  defaultSeo {\n  title,\n  description,\n  noIndex,\n  ogImage\n},\n  headerLinks[]{\n    _key,\n    linkType,\n    url,\n    openInNewTab,\n    reference->{ name, \"slug\": slug.current }\n  },\n  footerLinks[]{\n    _key,\n    linkType,\n    url,\n    openInNewTab,\n    reference->{ name, \"slug\": slug.current }\n  }\n}": SITE_SETTINGS_QUERY_RESULT;
    "*[_type == \"project\"] | order(title asc) {\n  _id,\n  title,\n  \"slug\": slug.current,\n  description,\n  coverImage\n}": PROJECTS_QUERY_RESULT;
    "*[_type == \"page\" && slug.current != \"home\" && (!defined(noIndex) || noIndex != true) && (!defined(seo.noIndex) || seo.noIndex != true)].slug.current": PAGE_SLUGS_QUERY_RESULT;
    "*[_type == \"page\" && (!defined(noIndex) || noIndex != true) && (!defined(seo.noIndex) || seo.noIndex != true)]{\n  \"slug\": slug.current,\n  _updatedAt\n}": SITEMAP_PAGES_QUERY_RESULT;
    "*[_type == \"page\" && slug.current == \"home\"][0]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  noIndex,\n  seo {\n  title,\n  description,\n  noIndex,\n  ogImage\n},\n  content[]{\n    _key,\n    _type,\n    _type == \"hero\" => {\n      heading,\n      body,\n      image,\n      cta {\n        level,\n        link {\n  linkType,\n  url,\n  openInNewTab,\n  reference->{ name, \"slug\": slug.current }\n}\n      }\n    },\n    _type == \"features\" => {\n      heading,\n      items[]{ title, description, icon }\n    },\n    _type == \"faq\" => {\n      heading,\n      items[]{ question, answer }\n    },\n    _type == \"contactSection\" => {\n      heading,\n      body,\n      showContactDetails\n    },\n    _type == \"projectsGrid\" => {\n      heading,\n      intro\n    },\n    _type == \"testimonial\" => {\n      quote,\n      author,\n      role,\n      image\n    },\n    _type == \"imageBlock\" => {\n      asset,\n      altText,\n      caption\n    },\n    _type == \"richText\" => {\n      content\n    },\n    _type == \"cta\" => {\n      level,\n      link {\n  linkType,\n  url,\n  openInNewTab,\n  reference->{ name, \"slug\": slug.current }\n}\n    }\n  }\n}": HOME_PAGE_QUERY_RESULT;
    "*[_type == \"page\" && slug.current == $slug][0]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  noIndex,\n  seo {\n  title,\n  description,\n  noIndex,\n  ogImage\n},\n  content[]{\n    _key,\n    _type,\n    _type == \"hero\" => {\n      heading,\n      body,\n      image,\n      cta {\n        level,\n        link {\n  linkType,\n  url,\n  openInNewTab,\n  reference->{ name, \"slug\": slug.current }\n}\n      }\n    },\n    _type == \"features\" => {\n      heading,\n      items[]{ title, description, icon }\n    },\n    _type == \"faq\" => {\n      heading,\n      items[]{ question, answer }\n    },\n    _type == \"contactSection\" => {\n      heading,\n      body,\n      showContactDetails\n    },\n    _type == \"projectsGrid\" => {\n      heading,\n      intro\n    },\n    _type == \"testimonial\" => {\n      quote,\n      author,\n      role,\n      image\n    },\n    _type == \"imageBlock\" => {\n      asset,\n      altText,\n      caption\n    },\n    _type == \"richText\" => {\n      content\n    },\n    _type == \"cta\" => {\n      level,\n      link {\n  linkType,\n  url,\n  openInNewTab,\n  reference->{ name, \"slug\": slug.current }\n}\n    }\n  }\n}": PAGE_QUERY_RESULT;
  }
}

